### ISSUE TITLE
PullToRefreshListView的GridView，分页时，下一页如果只有一个数据不能马上显示，需要稍微往上拖动下，再往下拖动才可显示出数据，是怎么回事呢？

### ISSUE THREAD

**Issue by leafseelight** [johannilsson/android-pulltorefresh#100]
PullToRefreshListView的GridView，分页时，下一页如果只有一个数据不能马上显示，需要稍微往上拖动下，再往下拖动才可显示出数据，是怎么回事呢？

**Comment by johannilsson** [comment]
Hi @leafseelight this library is over 6 years old and is not maintained anymore, a modern approach to this pattern is instead available in the Android support libraries.

**Comment by leafseelight** [comment]
Nice to receive your reply ! Thank you ! This issue is found from a old project.Now I have been used recycleview for instead. I just want to know to  whether someone have encountered or solve this problem.Best wishes !（Ps:Forgive me for my weak English）
