### ISSUE TITLE
Needs to handle other OnScrollListener objects

### ISSUE THREAD

**Issue by heliodor** [johannilsson/android-pulltorefresh#14]
If anyone calls setOnScrollListener(), this implementation stops working.

Here's the reasoning and the fix (tested in my own implementation).

PullToRefreshlistView.java contains

``` Java
setOnScrollListener(this);
```

If anyone calls setOnScrollListener() from outside, the functionality in our own listener gets bypassed, leaving the list with the tap-to-refresh functionality and disabling the whole pulling magic.

To fix:

``` Java
private OnScrollListener mScrollListener;

@Override
public void setOnScrollListener(OnScrollListener listener) {
    if (!this.equals(listener)) {
        mScrollListener = listener;
    }
    else {
        super.setOnScrollListener(listener);
    }
}

@Override
public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {
    ...
    if (mScrollListener != null) {
        mScrollListener.onScroll(view, firstVisibleItem, visibleItemCount, totalItemCount);
    }
}

@Override
public void onScrollStateChanged(AbsListView view, int scrollState) {
    ...
    if (mScrollListener != null) {
        mScrollListener.onScrollStateChanged(view, scrollState);
    }
}
```

It looks like on-scroll is the only listener being set from inside, so this should be the only instance of this type of problem.

**Comment by johannilsson** [comment]
Thank you, will fix as soon as possible.

**Comment by heliodor** [comment]
You're welcome. Awesome component!
