### ISSUE TITLE
Expendable listview

### ISSUE THREAD

**Issue by hades-6** [johannilsson/android-pulltorefresh#15]
I changed the implementation to support expendable listview but even though it compiles it doesn't work. It displays the control and the pull to refresh function does get called but the animations do not work. I tried it on 1.6 and 2.3.4. 

I hope you can get it work on expendable listviews as well. Would be very useful.

**Comment by johannilsson** [comment]
Hi, sorry for not commenting on this earlier. I have no plans to add support for `ExpandableListView` at the moment.

**Comment by hades-6** [comment]
That's ok. I got it working :)
