### ISSUE TITLE
Tap to refresh flashes

### ISSUE THREAD

**Issue by cschloesser** [johannilsson/android-pulltorefresh#20]
Hey there,
first of all: i can reproduce this with the example app!
Tested OS: Android 2.2, 2.3.3 and 2.3.4 - Emulator and Nexus One!

This is what happens:
You need to extend the example app by an onItemClickListener and a second activity!
When you start the app, and click an item (NOT the first), the tap to refresh button appears on the top of the list, then of course, the second activity starts.
When you return (by pressing the back key), the "Tap to refresh" stays on top, although the list has enough items.

I use this onListItemClick Listener:
@Override
protected void onListItemClick(ListView l, View v, int position, long id) {
    super.onListItemClick(l, v, position, id);
    Intent i = new Intent(this, Second.class);
    startActivity(i);
}

Really easy to reproduce. Any chance this could be fixed?

Best regards

chris

EDIT: Dont scroll the list before! this fixes the problem temporarily. You must click one of the items you can see, as I said, not the first! ;)

**Comment by johannilsson** [comment]
Sorry for commenting on this earlier. I can reproduce the error, however this seems to be a problem with the list view in general and not actually related to the pull to refresh widget even if it manifest it self quite bad here. I plan to rewrite some parts of how the header is added which will remove the need for a "tap to refresh" view. I'm sorry but I will not fix this issue now, but if you like you can patch it yourself by calling `scrollListBy(1, 0);` from setAdapter and `onAttachedToWindow`.
