### ISSUE TITLE
Tap to refresh is shown on every list item clicked

### ISSUE THREAD

**Issue by almozavr** [johannilsson/android-pulltorefresh#25]
OnItemClick makes list to show tap to refresh header on Android 2.2. Lets try to find out why!

**Comment by almozavr** [comment]
Sorry, I found a similar issue being closed later.

**Comment by yava555** [comment]
I also found this problem, use the latest source code.

when you first click list item,"Tap to refresh" will be shown.

Android 2.3.7

**Comment by bostone** [comment]
Hey, why this is closed? In my app when I load the list this "Tap to refresh" is showing almost constantly. It is shown on the start and after the refresh. Any way to get rid of it? I'm using build johannilsson-android-pulltorefresh-f090768
