### ISSUE TITLE
Trying to include in a project targeted for API 8

### ISSUE THREAD

**Issue by neekers** [johannilsson/android-pulltorefresh#27]
Any clue how to fix this in my project setup?

Description Resource    Path    Location    Type
The method onClick(View) of type PullToRefreshListView.OnClickRefreshListener must override a superclass method PullToRefreshListView.java  /OurHistree Test/com_markupartist_android_widget_pulltorefresh_src/com/markupartist/android/widget  line 413    Java Problem
The method onScroll(AbsListView, int, int, int) of type PullToRefreshListView must override a superclass method PullToRefreshListView.java  /OurHistree Test/com_markupartist_android_widget_pulltorefresh_src/com/markupartist/android/widget  line 309    Java Problem
The method onScrollStateChanged(AbsListView, int) of type PullToRefreshListView must override a superclass method   PullToRefreshListView.java  /OurHistree Test/com_markupartist_android_widget_pulltorefresh_src/com/markupartist/android/widget  line 350    Java Problem

**Comment by johannilsson** [comment]
Hi. Could it be that you're trying to comple with Java 5 instead of Java 6? Seems like it's complains on some interfaces, annotations on interface was introduced in Java 6 if I recall correct.

**Comment by neekers** [comment]
It built! I will let you know when I can test this on my dev build later tonight.  Thanks a bunch for the quick response

**Comment by johannilsson** [comment]
Sweet, glad I could help.
