### ISSUE TITLE
Remove Tap To Refresh button

### ISSUE THREAD

**Issue by h-unterp** [johannilsson/android-pulltorefresh#29]
The Twitter app can do pull to refresh on 1 item, so can this !

**Comment by ovy9086** [comment]
I would like this to. Any ideas/news?

**Comment by amigax** [comment]
Ive just spent an entire day trying to get rid of this and cant do it - I simply dont want it to appear !! when i drag list down it disappears and all is perfect, so why the hell is it even there in the first place and why cant I even hack this to hide it!? Any ideas.... very frustrated

**Comment by d-krey** [comment]
did you solve the issue? i have similar problem

**Comment by tobiasheine** [comment]
me too, would be great if anyone could post a solution...

**Comment by mattgapadmi** [comment]
Use the scrollfix_for_short_list branch, but if you'll need to apply this patch to it so that scrolling works on Jelly Bean (4.1):

https://github.com/johannilsson/android-pulltorefresh/commit/16484755e56aeb5fd06494a88e3e61a4d932a066

**Comment by 2026-AndroidDev** [comment]
i have similar problem amd worked for a day ,but can't find any solution.
please post a solution if anyone have.

i found this: but dont know how to use

http://www.joshdale.net/2012/03/01/hiding-pulltorefreshlistview-headers/

please let me know if anyone can do something.

**Comment by johannilsson** [comment]
There's a draft implementation of this in the short list branch. Thank.
