### ISSUE TITLE
GridView support

### ISSUE THREAD

**Issue by dmarcato** [johannilsson/android-pulltorefresh#32]
Hi, this is fantastic but it only works for ListView... Would it be possible to adapt it for a GridView?
Thanks! :)

**Comment by johannilsson** [comment]
Hi,thank you! The current implementation depends on`ListView` so I'm afraid this is not possible or planned at this moment.

**Comment by Amokrane** [comment]
The issue is that the `GridView` widget does not provide any `addHeaderView` method. This is pissing me off, as my app relies heavily on `GridViews`.  Johan, have you thought on any trick that would solve this issue?

**Comment by johannilsson** [comment]
Hi @amokrane there's a recently released [library](https://github.com/chrisbanes/Android-PullToRefresh/) that has support for `GridView`S, you might want to give that a try. Haven't looked at the source code (that much) for that project yet, but it might be possible to port that into this library as well.

**Comment by Amokrane** [comment]
Thank you so much for showing me this project. I almost added a refresh button to the _actionbar_ in desperation.

**Comment by johannilsson** [comment]
Pull request welcomed though :)

**Comment by Amokrane** [comment]
I will seriously consider it, thanks :)
