### ISSUE TITLE
Can we make pulltorefresh from bottom instead top?

### ISSUE THREAD

**Issue by trietbui85** [johannilsson/android-pulltorefresh#35]
It sounds weird, but I want to pull up to refresh. It means after scrolling to bottom of Listview, now I will pull up and release to perform pulltorefresh.

Can we do it?

P/S: it's not an issue but just a suggestion.

Thanks.
anticafe

**Comment by paradoxxjm** [comment]
First, thank you for a great library!

Secondly, I think being able to have pulltorefresh work from the bottom, which I guess makes it pushtorefresh, would be a great development. Keep up the work!

**Comment by chrisbanes** [comment]
I recently added this to my Pull to Refresh library: http://www.senab.co.uk/2011/12/23/pull-up-to-refresh/

**Comment by trietbui85** [comment]
Thanks man ^^. It looks great ;)

Btw, merry Christmas.

**Comment by johannilsson** [comment]
Great work @chrisbanes, I'm closing this issue.
