### ISSUE TITLE
Crash on 10.1 Tablet

### ISSUE THREAD

**Issue by barisatbas** [johannilsson/android-pulltorefresh#38]
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1863)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1287)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.app.Activity.dispatchTouchEvent(Activity.java:2309)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1836)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.View.dispatchPointerEvent(View.java:4689)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2365)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.view.ViewRoot.handleMessage(ViewRoot.java:2034)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.os.Looper.loop(Looper.java:132)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at android.app.ActivityThread.main(ActivityThread.java:4028)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at java.lang.reflect.Method.invokeNative(Native Method)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at java.lang.reflect.Method.invoke(Method.java:491)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
10-31 12:23:31.100: E/AndroidRuntime(2626):     at dalvik.system.NativeStart.main(Native Method)
10-31 12:23:31.100: W/ActivityManager(288):   Force finishing activity com.shopamani.shpmn/.activities.TumKampanyalarActivity

**Comment by johannilsson** [comment]
Hi, thank you for the report. I don't have access to any tablet I'm afraid, and the emulator is terrible slow. Can you reproduce the crash in the example app too?

**Comment by barisatbas** [comment]
Full Exception output :

10-31 14:04:20.730: E/AndroidRuntime(6179): FATAL EXCEPTION: main
10-31 14:04:20.730: E/AndroidRuntime(6179): java.lang.IllegalArgumentException: historyPos out of range
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.MotionEvent.nativeGetAxisValue(Native Method)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.MotionEvent.getHistoricalY(MotionEvent.java:1828)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.markupartist.android.widget.PullToRefreshListView.applyHeaderPadding(PullToRefreshListView.java:224)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.markupartist.android.widget.PullToRefreshListView.onTouchEvent(PullToRefreshListView.java:195)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.View.dispatchTouchEvent(View.java:4621)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1554)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1320)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1560)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1333)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1863)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1287)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.app.Activity.dispatchTouchEvent(Activity.java:2309)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1836)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.View.dispatchPointerEvent(View.java:4689)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2365)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.view.ViewRoot.handleMessage(ViewRoot.java:2034)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.os.Looper.loop(Looper.java:132)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at android.app.ActivityThread.main(ActivityThread.java:4028)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at java.lang.reflect.Method.invokeNative(Native Method)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at java.lang.reflect.Method.invoke(Method.java:491)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
10-31 14:04:20.730: E/AndroidRuntime(6179):     at dalvik.system.NativeStart.main(Native Method)

Sample Project
https://rapidshare.com/files/1926490470/PullToRefreshListViewTest.rar

**Comment by johannilsson** [comment]
Thank you, this looks related to #37. Could you try the patch that's posted on that issue and see how that works for you?

**Comment by barisatbas** [comment]
Thanks, this patch fixed the issue..

**Comment by johannilsson** [comment]
Closed with bef2a2ad0e14f544fd12043f21b6c76853ba08a9
