### ISSUE TITLE
Tried to build with Eclipse, getting errors? 

### ISSUE THREAD

**Issue by efontana** [johannilsson/android-pulltorefresh#46]
Description Resource    Path    Location    Type
The method onClick(View) of type PullToRefreshListView.OnClickRefreshListener must override a superclass method PullToRefreshListView.java  /pulltorefresh/src/com/markupartist/android/widget  line 388    Java Problem
The method onScroll(AbsListView, int, int, int) of type PullToRefreshListView must override a superclass method PullToRefreshListView.java  /pulltorefresh/src/com/markupartist/android/widget  line 277    Java Problem
The method onScrollStateChanged(AbsListView, int) of type PullToRefreshListView must override a superclass method   PullToRefreshListView.java  /pulltorefresh/src/com/markupartist/android/widget  line 321    Java Problem

**Comment by johannilsson** [comment]
You probably using Java 1.5, try with 1.6 instead.

**Comment by efontana** [comment]
That was it, thanks.  BTW: I'm porting this to Mono for Android.

**Comment by johannilsson** [comment]
Sweet! That sounds awesome - haven't seen Mono for Android before, please let us know how the progress goes.

**Comment by efontana** [comment]
I just finished it!

-----Original Message-----
