### ISSUE TITLE
Does not work on Android 2.1 Update1.

### ISSUE THREAD

**Issue by MantaMay** [johannilsson/android-pulltorefresh#5]
Not sure if you are totally supporting 2.1, but considering it still makes up a good percentage of the market thought you might want to be aware, when scrolling in 2.1 the list slowly disappears, this appears to be an issue with your ScrollListBy. I have confirmed this in both the AVD, and a Device.

**Comment by johannilsson** [comment]
I've seen this too, I thought that it should work out of the box with the fallback to scrollBy but it looks like it didn't. I added the scrollListBy method to be able to support lower versions than 2.2 and that intention is definitely still there, but current support is only for 2.2 though.

**Comment by MantaMay** [comment]
Found the answer ScrollBy and ScrollTo aren't supported in ListViews pre Froyo, you will need to use setSelection(int)... This was confirmed by Romain Guy. This may not be ideal, but it will work... currently the way ScrollBy and ScrollTo work in pre Froyo ListView is that it will shift the entire View, not the items inside the list!!!

**Comment by johannilsson** [comment]
Oh that explains the strange behaviour thanks for the clarification. Will experiment with setSelection as soon as I find the time. I'll open this issue again so we have an issue to track this with.

**Comment by johannilsson** [comment]
Closed by e06ad15a275ed8827237ef2106a68e8fd42b5277
