### ISSUE TITLE
How to set Typeface of text in list

### ISSUE THREAD

**Issue by signalarun** [johannilsson/android-pulltorefresh#70]

**Comment by johannilsson** [comment]
Hey, you should be able to style the various elements using standard styles.

**Comment by signalarun** [comment]
I want to set a font for Indian languages.

**Comment by johannilsson** [comment]
Maybe this [SO question](http://stackoverflow.com/questions/7858860/android-change-font-type-of-application) could help.

**Comment by signalarun** [comment]
I want to set it in pulltorefreshlist

**Comment by johannilsson** [comment]
You need to modify the related `TextView`s manually to get this to run.

**Comment by signalarun** [comment]
What is the id for textview in list of pulltorefreshlist
