### ISSUE TITLE
scroll problem 

### ISSUE THREAD

**Issue by lugenvn** [johannilsson/android-pulltorefresh#78]
[PullToRefreshWebViewActivity] when I change the link in your example to "https://github.com/chrisbanes/Android-PullToRefresh" and swipe up and down several times. I get this screen. the bottom loading bar keep showing like that when i swipe up and release it for continue scroll down. when it hit the end of view. it got this screen and keep this with no change or animation to close the bar. 

I think it's the library's problem.

![screenshot_2014-02-13-09-47-26](https://f.cloud.github.com/assets/1548463/2156364/c681dcee-9459-11e3-986a-b3931df6de06.jpg)

**Comment by johannilsson** [comment]
Hi @lugenvn, thanks for the report. I'm closing this issue since it seems like it's related to @chrisbanes project rather than this implementation.
