### ISSUE TITLE
PullToRefreshArrow flip animation improvement

### ISSUE THREAD

**Issue by jerrellmardis** [johannilsson/android-pulltorefresh#8]
This is more of an improvement request than a bug/issue.

I noticed since the last commit that the ic_pulltorefresh_arrow.png is flipped only when then top of the list reaches the top of the actual image. It would be nice if it flipped when the top of the list is roughly 10dip above the image. For an example, look at when the arrow is flipped in official Twitter app. I believe up until this point the arrow would flip when the top of the list was a few dip above the image as well.

Sorry, I didn't have time to look into a solution but hopefully if you all agree, this is a simple fix.

**Comment by johannilsson** [comment]
Thanks for the report! I had the image replaced and added versions for mdpi and ldpi, could be that the old image had a padding included. I quickly fixed it for now by used adding a arbitrary value, guess we can tweak that until we're satisfied.
