### ISSUE TITLE
Works only with linked list

### ISSUE THREAD

**Issue by saritagandhi** [johannilsson/android-pulltorefresh#87]
Hi i  am trying to implement in my project in which i am using custom list view with BaseAdapter but its not working properly its showing tap to refresh text always and scroll bar is not working for list

**Comment by johannilsson** [comment]
Thanks for your comment, is this related to #88?

**Comment by saritagandhi** [comment]
Thanks, yes. It is working with large number of item.

**Comment by johannilsson** [comment]
This is by design, there's an alternative implementation that @chrisbanes have done that you can get from here, https://github.com/chrisbanes/ActionBar-PullToRefresh/

Thanks for the report.

**Comment by saritagandhi** [comment]
Thanks for reply this code helps me a lot in implementation in my app .
