### ISSUE TITLE
Sometimes getting tap to refresh

### ISSUE THREAD

**Issue by kalvish21** [johannilsson/android-pulltorefresh#91]
I have a list with many items, sometimes after pull to refresh is done, i'm getting tap to refresh?

How can I disable the tap to refresh entirely?

**Comment by RajivDaffodil** [comment]
I am also facing this prob.
this tap to refresh looks very bad please guide to remove it entirely.

**Comment by kalvish21** [comment]
I don't think this project is maintained any longer. Best is to move away from it or to fork the repo and continue from there.
